### ISSUE TITLE
Figured id create a seperate post about clouds

### ISSUE THREAD

**Issue by falcon470** [drobie22/RSS-Reborn-Installer#10]
So low on money so cant get volumetic clouds from black rock this is more of a question then a bug report, are there suppoesed to be clouds? without that? i can get em by doing some thing the manual install doent recomend which is have ckan install rssve after the installer finishes what is the recommended step? or isss what im doing correct

**Comment by drobie22** [comment]
RSSVE clouds will be implemented by default in next release if blackracks is not selected. For now just make sure you install RSSVE after the installer runs

**Comment by falcon470** [comment]
ok cool ty

**Comment by falcon470** [comment]
thats about all i neeed for this one
