### ISSUE TITLE
I used Installer install the mods normally, but it doesn't work

### ISSUE THREAD

**Issue by zhouyiqing0304** [drobie22/RSS-Reborn-Installer#11]
**Describe the bug**

**Attach Log**
Please see Repo home page for instructions on how to find your latest log. 

**Add Label**
Please add a label to best categorize your issue. Default is `Bug`.

![image](https://github.com/user-attachments/assets/f495949a-49ba-4b68-9a2e-86c88bc3e7d4)

then the KSP.log show this
[EXC 17:53:37.018] NullReferenceException: Object reference not set to an instance of an object
	Scatterer.AtmoPreprocessor.ReleaseTextures () (at <fdee3865bbd54560b3f1af491ef04bf6>:0)
	Scatterer.AtmoPreprocessor.OnDestroy () (at <fdee3865bbd54560b3f1af491ef04bf6>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[LOG 17:53:37.028] ScaleModList: listSize 41 maxListSize 1415
[LOG 17:53:37.057] [Scatterer][Debug] No changes to main config, skipping saving.
[EXC 17:53:37.093] NullReferenceException: Object reference not set to an instance of an object
	Kopernicus.Injector.OnDestroy () (at <0708e1bc41b144fe8a3d33f3f39c4d0b>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by zhouyiqing0304** [comment]
@drobie22

**Comment by zhouyiqing0304** [comment]
I set my ACCESS TOKEN rightly

**Comment by drobie22** [comment]
How did you run your setup?

Did you use CKAN for your normal install?

Did it work before using the RSS Reborn installer?

Did the installer give you any errors? Follow the instructions on the installer GitHub page for getting the installer log.

**Comment by zhouyiqing0304** [comment]
Now it works, when I use 16k texture
It works, I think it was the problem of downloading
