### ISSUE TITLE
 I load the game but get stuck on an infinite black loading screen with spinning planets

### ISSUE THREAD

**Issue by shujijiangya** [drobie22/RSS-Reborn-Installer#12]
https://imgur.com/a/vbbpgPi

**Comment by drobie22** [comment]
How did you install RSS Reborn?

Did you run the game with no issues before RSS Reborn was installed?

**Comment by shujijiangya** [comment]
> 你是怎么安装 RSS Reborn 的？
> 
> 在安装 RSS Reborn 之前，您是否运行了游戏没有问题？

I installed it manually. Before that, the game was running normally.

**Comment by drobie22** [comment]
So this GitHub repo is for the automatic installer. For manual help I recommend ballisticfox's discord server. 

That being said, sounds like your install is either missing the squad folders, has the wrong kopernicus fork, or needs parallax reinstalled.

**Comment by drobie22** [comment]
https://discord.gg/H6JMRyPxpT
I think
