### ISSUE TITLE
Download/Installation Failing on Parallax Step

### ISSUE THREAD

**Issue by PugglesLesser** [drobie22/RSS-Reborn-Installer#15]
Using Blackrack's volumetrics, with RP-1 installed through CKAN (Express installer) and verified working, attempting to install using the installer functions normally until the current file reaches Parallax-2.0.8, where it pops up with the error "Download Failed: Cannot create file ...\RSSRebornDownloads\Parallax-2.0.8.zip check your connection and click retry..."

I have downloaded the latest RaymarchedVolumetrics from BlackRack's Patreon and correctly linked to it in the installer.

My connection is good, I can manually download that version of Parallax from the link specified in the logs without issue. It also is not a file permissions issue (tried correcting file perms). Retrying does not work. 

Also, I have Parallax continued early access release2, can I use this instead? Will it function? 

Logs:

[Setup Log 2024-10-31 #001.txt](https://github.com/user-attachments/files/17590625/Setup.Log.2024-10-31.001.txt)

**Comment by drobie22** [comment]
Could be a GitHub rate access limit issue. See the readme for instructions on how to increase your github download limit. 

As of this moment Parallax continue is not compatible with Reborn, but the devs are working on it.

**Comment by PugglesLesser** [comment]
Followed the instructions then retried the installer and it has the same issue unfortunately.

**Comment by drobie22** [comment]
> It also is not a file permissions issue (tried correcting file perms).

What did you do to change perms?

**Comment by stockofcrates** [comment]
Have the same problem, installed rp-1 via CKAN, except I do not use the volumetric clouds. 

I did increase the rate limit, still had the same problem.

**Comment by stockofcrates** [comment]
> Have the same problem, installed rp-1 via CKAN, except I do not use the volumetric clouds.
> 
> I did increase the rate limit, still had the same problem.

Nevermind, I figured out I had the directory downloading to a non-existant file.

**Comment by Toucanto** [comment]
Yeah, if anyone has this issue in the future, i fixed it by making sure you get the directory correct. The installer doesnt auto-detect your KSP folder.

so for me the installer said that KSP was at: "C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program"
when it was actually at: "G:\SteamLibrary\steamapps\common\Kerbal Space Program\GameData"
