### ISSUE TITLE
Not an issue- but installing Volumetrics after using the download wizard?

### ISSUE THREAD

**Issue by Raidriar01** [drobie22/RSS-Reborn-Installer#16]
I've had this mod for a bit now but only just recently got Blackrack's volumetric cloud mod, and I remember there being the option to select it in setup wizard, but what should I do since I want to install it after initially installing this mod?

**Comment by drobie22** [comment]
Just run the installer again. If you don't want to reinstall textures, just select "none" on the resolution drop down
