### ISSUE TITLE
Installer not recognizing WinRAR or 7Zip

### ISSUE THREAD

**Issue by MountainEagle101** [drobie22/RSS-Reborn-Installer#17]
![image](https://github.com/user-attachments/assets/7eafc42e-891c-4ff3-99d8-7c4cd0ba1545)

Installed WinRAR and restarted the PC. WinRAR works fine

**Comment by YeYe12346790** [comment]
This is still a problem

**Comment by drobie22** [comment]
> This is still a problem

Can you start a new issue thread with your log please?
