### ISSUE TITLE
ground level to low 

### ISSUE THREAD

**Issue by TianNilssen** [drobie22/RSS-Reborn-Installer#18]
When using the Real Solar System (RSS) mod (v20.1.3.0) along with the RSS Reborn installer (v1.2.2) in KSP version 1.12.5.3190, the Kerbal Space Center (KSC) appears to "hover" above the ground. This issue occurs with and without the True Volumetric Clouds (Raymarched Volumetrics Early Access, release 16_07_24) by Blackrack, so the problem seems unrelated to that specific cloud mod. 

![Screenshot 2024-11-11 231446](https://github.com/user-attachments/assets/6ca14c99-08a3-46ef-982f-ce213acb6384)
![Screenshot 2024-11-11 231627](https://github.com/user-attachments/assets/07c67082-03d3-40e7-98be-bceb71a59280)
![Screenshot 2024-11-11 232756](https://github.com/user-attachments/assets/1c004502-69f3-40e7-9ae1-c34d58e2c3d5)
**Attach Log**
[without RaymarchedVolumetricsEarlyAccess.txt](https://github.com/user-attachments/files/17723492/whitout.RaymarchedVolumetricsEarlyAccess.txt)
[with RaymarchedVolumetricsEarlyAccess.txt](https://github.com/user-attachments/files/17723493/with.RaymarchedVolumetricsEarlyAccess.txt)

**Comment by drobie22** [comment]
Appreciate all the detail!

What launchsite is this? Is it RSS only? Or do you have RP-1 etc

**Comment by TianNilssen** [comment]
Only RSS, and a new KsP install

**Comment by drobie22** [comment]
I recommend asking on ballisticfox's discord. Lmk if you need a link
