### ISSUE TITLE
won't work even tho I have both Winrar and 7zip installed

### ISSUE THREAD

**Issue by Vomitspit1** [drobie22/RSS-Reborn-Installer#20]
**Describe the bug**

**Attach Log**
Please see Repo home page for instructions on how to find your latest log. 

**Add Label**
Please add a label to best categorize your issue. Default is `Bug`.

**Comment by drobie22** [comment]
Is 7 zip and or winrar installed in their default file locations? i.e. program files

**Comment by Vomitspit1** [comment]
Oh, that's the issue! I had it installed in my hard drive
Thanks!
