### ISSUE TITLE
When I tried to download it, I ran it and a warning from the Windows firewall came out. Is this safe?

### ISSUE THREAD

**Issue by glichdude2011** [drobie22/RSS-Reborn-Installer#21]
**Is your feature request related to a problem with the installer (_not RSS Reborn itself_)? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by drobie22** [comment]
As of right now, the installer has 4,000+ downloads and I haven't heard of any malicious issues. 

All code is open source, and if you are concerned you can build the exe yourself using inno setup. 

Otherwise, I recommend asking on Ballisticfox's discord for user testimonies.
