### ISSUE TITLE
Error extracting message

### ISSUE THREAD

**Issue by Xzznnn** [drobie22/RSS-Reborn-Installer#7]
Sometimes during the extracting process it displays an error message and things don't get merged into the GameData folder

**Comment by drobie22** [comment]
Please submit your log

**Comment by falcon470** [comment]
This is cause for some reason some files are corrupted i found the files and thats whats going on

**Comment by falcon470** [comment]
hopefully i can just rerun installer and it will correct it

**Comment by drobie22** [comment]
The 0 mb file size is a bug and will be fixed in next release. You can still select them. If you are getting errors, the log def helps. It could be a rate limit from GitHub. Info about rate limits and logs is on the home page of this repo

**Comment by falcon470** [comment]
I posted another bug report on a differnt issue my same log is there i selected 48 k earth and every thing worked fine

**Comment by falcon470** [comment]
Seems to show correct size if you deselect earth 64k and reselect it

**Comment by zhouyiqing0304** [comment]
![image](https://github.com/user-attachments/assets/4d038954-42d1-47da-be11-526721d04b96)

**Comment by drobie22** [comment]
> ![image](https://github.com/user-attachments/assets/4d038954-42d1-47da-be11-526721d04b96)
> 
> 

See the readme for instructions on this issue

**Comment by zhouyiqing0304** [comment]
saw, then I understanded

**Comment by luanxiang123** [comment]
I have 7-ZIP and WinRAR installed on my computer, but I still get an error
![Uploading 屏幕截图 2024-08-28 212140.png…]()

**Comment by drobie22** [comment]
This is most likely a download issue, not an extracting issue. Fixed in [v1.2.0](https://github.com/drobie22/RSS-Reborn-Installer/releases/latest)
