### ISSUE TITLE
Not getting clouds, 

### ISSUE THREAD

**Issue by falcon470** [drobie22/RSS-Reborn-Installer#8]
Dont have volumetric clouds getting invalid name on eve, i can attach a log if needed mabey theres some thing i got to turn on

**Comment by drobie22** [comment]
Did you include the zipped raymarched clouds from blackrack? Log plz

**Comment by falcon470** [comment]
I cant get that, 1 worried about performance issues and i went ahead and installed rssve from ckan it put the normal ones on, i may try the clouds later worried about performance issues

**Comment by drobie22** [comment]
Yeah if you don't include his volumetric clouds then you won't have volumetric clouds lol. RSSVE clouds will be implemented by default in next release.
