### ISSUE TITLE
Flickering pixels, so far only tested on kerbin

### ISSUE THREAD

**Issue by falcon470** [drobie22/RSS-Reborn-Installer#9]
So im getting flickering pixels when launching from kerbin is is this normal, ill post the log if needed for this one, mabey its a setting i dont have turned on useing 48 k kerbin, with eve scatter clouds

**Comment by falcon470** [comment]
[Setup Log 2024-08-07 #001.txt](https://github.com/user-attachments/files/16529194/Setup.Log.2024-08-07.001.txt)

**Comment by drobie22** [comment]
Flickering pixels? Do you have a video? Might be a TAA issue, outside the scope of the installer

**Comment by drobie22** [comment]
There's a few errors related to extracting files here in your log. I see you're using winrar, try 7 zip instead

**Comment by falcon470** [comment]
i can try 7 zip thought installeer didnt care, and im not sure the issues as bad i clicked on several options in the grapics menu and it seems to not go away but go away with height horiozn at ground level is worse, will re run the installer after getting 7 zip and see what it does

**Comment by falcon470** [comment]
had an error on jupiter 16 k

**Comment by falcon470** [comment]
[Setup Log 2024-08-07 #001.txt](https://github.com/user-attachments/files/16530517/Setup.Log.2024-08-07.001.txt)

**Comment by falcon470** [comment]
can i get that file seperatrely somewhere?

**Comment by drobie22** [comment]
Try installing Jupiter on its own https://github.com/RSS-Reborn/RSS-Jupiter/releases

**Comment by falcon470** [comment]
not getting clouds according to manual install were supposed to be going to blackrocks pateron for those, ive been installing rssve on its own and from ckan for some things trying to see if im missing something

**Comment by falcon470** [comment]
And no clouds can work around that issue but its my understanding that clouds are supposed to work without my work around, and mabey why im getting the flickering textures im thinking, doing an automatic install then gonna paste over it with all the manual intall stuff to make sure the automatic is doing it right

**Comment by falcon470** [comment]
every things running again, ive realized its the water that causeing the problem any ideas? grapics settings to change, seems to be no way to adjust taa

**Comment by drobie22** [comment]
It's in TUFX, change it to SMAA

**Comment by falcon470** [comment]
got ya i did not have tufx installing it now, ill close as if this does not work its all i can do and ill just deal with it from here
